// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POS_Retails.Entity;

#nullable disable

namespace PosWebApplication.Migrations
{
    [DbContext(typeof(pos_saas_entities))]
    [Migration("20260922070030_noError")]
    partial class noError
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PosWebApplication.Entity.comment", b =>
                {
                    b.Property<int>("c_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("c_id"));

                    b.Property<string>("comments")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime");

                    b.Property<int>("p_id")
                        .HasColumnType("int");

                    b.Property<int>("u_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime");

                    b.HasKey("c_id");

                    b.HasIndex("p_id");

                    b.HasIndex("u_id");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("PosWebApplication.Entity.post", b =>
                {
                    b.Property<int>("p_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("p_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime");

                    b.Property<int>("created_by")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<string>("public_flag")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("title")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime");

                    b.Property<int>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("p_id");

                    b.HasIndex("created_by");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("PosWebApplication.Entity.user", b =>
                {
                    b.Property<int>("u_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("u_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime");

                    b.Property<int>("created_by")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("img")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("password")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime");

                    b.Property<int>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("u_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PosWebApplication.Entity.comment", b =>
                {
                    b.HasOne("PosWebApplication.Entity.post", "post")
                        .WithMany("comments")
                        .HasForeignKey("p_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PosWebApplication.Entity.user", "user")
                        .WithMany("comments")
                        .HasForeignKey("u_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("post");

                    b.Navigation("user");
                });

            modelBuilder.Entity("PosWebApplication.Entity.post", b =>
                {
                    b.HasOne("PosWebApplication.Entity.user", "user")
                        .WithMany("posts")
                        .HasForeignKey("created_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("PosWebApplication.Entity.post", b =>
                {
                    b.Navigation("comments");
                });

            modelBuilder.Entity("PosWebApplication.Entity.user", b =>
                {
                    b.Navigation("comments");

                    b.Navigation("posts");
                });
#pragma warning restore 612, 618
        }
    }
}
